### ISSUE TITLE
Various errors were reported when building with xmake

### ISSUE THREAD

**Issue by taomh** [hugeproblem/nged#2]
![屏幕截图 2024-01-30 110932](https://github.com/hugeproblem/nged/assets/71888223/9cc08f12-58e7-42b7-b55f-f15113de7bd1)
![屏幕截图 2024-01-30 110921](https://github.com/hugeproblem/nged/assets/71888223/901d9857-c83e-4b50-8214-df5ba80fdf18)

**Comment by taomh** [comment]
Is it caused by my lack of certain prerequisites?

**Comment by hugeproblem** [comment]
please init submodules with `git submodule update --init`

**Comment by taomh** [comment]
Thank you.  The problem has been resolved, but the command you provided cannot pull all dependent libraries and I need to manually download them to the appropriate location.  I think it's a problem with GitHub😂.
