### ISSUE TITLE
如何加载显示中文字体？

### ISSUE THREAD

**Issue by lyongji** [hugeproblem/nged#3]
尝试修改 nged_imgui_fonts.cpp 文件中下列代码。
sansSerif = atlas->AddFontFromMemoryCompressedTTF(
    roboto_medium_compressed_data,
    roboto_medium_compressed_size,
    style.normalFontSize,
    nullptr,
    atlas->GetGlyphRangesChineseSimplifiedCommon() /* atlas->GetGlyphRangesGreek()*/);
————————
atlas->GetGlyphRangesGreek() 修改为atlas->GetGlyphRangesChineseSimplifiedCommon() 
中文显示从 ？？ 变为  ��
————————
在demo的main文件中.
void update()
  {
    static auto prev = std::chrono::system_clock::now();
    auto now = std::chrono::system_clock::now();
    auto dt = std::chrono::duration_cast<std::chrono::milliseconds>(now - prev);
    ImGui::PushFont(nged::ImGuiResource::instance().sansSerifFont);
    ImGui::Begin("Demo"); //添加的
    ImGui::Text("你好 ");//添加的
    ImGui::End();//添加的
    editor->update(dt.count() / 1000.f);
    editor->draw();
    ImGui::PopFont();
    prev = now;
  }

**Comment by find** [comment]
您需要换个字体，roboto medium 不带中文字符

**Comment by hugeproblem** [comment]
您需要换个字体，自带的字体不含中文字符
